#!/bin/sh
#
# chkconfig: 345 90 90
# description: - this service blocks the loadbalancer
 
case "$1" in
 
'start')
        /sbin/route add ns113.businesswire.com gw 127.0.0.1
        ;;
 
'stop')
        /sbin/route delete ns113.businesswire.com gw 127.0.0.1
        ;;
 
*)
        echo "Usage: $0 { start | stop }"
        exit 1
        ;;
esac